name: "Test deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - deploy_test_blog

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Prepare
        id: prepare
        run: |
          rm -rf .git .github .jenkins .gitignore .htaccess .prettierignore Changelog.md README.md web.config
          
          sed -i "s^name-database^${{ secrets.DB_NAME }}^" wp-config.php
          sed -i "s^user-database^${{ secrets.DB_USER }}" wp-config.php
          sed -i "s^password-database^${{ secrets.DB_PASS }}^" wp-config.php
          sed -i "s^host1^${{ secrets.DB_HOST }}^" wp-config.php
          sed -i "s^root1^${{ secrets.DOMAIN_NAME }}^" wp-config.php
          
          sed -i "s^some_key1^${{ secrets.SOMEKEY1 }}^" wp-config.php
          sed -i "s^some_key2^${{ secrets.SOMEKEY2 }}" wp-config.php
          sed -i "s^some_key3^${{ secrets.SOMEKEY3 }}^" wp-config.php
          sed -i "s^some_key4^${{ secrets.SOMEKEY4 }}^" wp-config.php
          sed -i "s^some_key5^${{ secrets.SOMEKEY5 }}^" wp-config.php
          sed -i "s^some_key6^${{ secrets.SOMEKEY6 }}^" wp-config.php
          sed -i "s^some_key7^${{ secrets.SOMEKEY7 }}^" wp-config.php
          sed -i "s^some_key8^${{ secrets.SOMEKEY8 }}^" wp-config.php
            
          mkdir -p /tmp/app

          tar -czpf /tmp/app/blog.tar.gz .
          echo ${{ secrets.SCRIPT }} > /tmp/app/deploy.sh

      - name: Copy files to host
        id: copy
        uses: appleboy/scp-action@v0.1.4
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "/tmp/app/blog.tar.gz,/tmp/app/deploy.sh"
          target: "/tmp/deploy/wp/"
      
      - name: Deploy
        id: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: sudo bash /tmp/deploy/wp/deploy.sh |& tee -a > /tmp/deploy/wp/deploy.log
