// Variables declaration

if ("${BRANCH_NAME}" == 'test.blog') {
	SECRET_ID_01   = "deploymentuser_pass"
	}

if ("${BRANCH_NAME}" == 'production.blog') {
	SECRET_ID_01   = "anton.rychenkov.test03.03"
	}

// Pipeline

pipeline {

    agent none

	stages {
	
		stage('Build') {

			agent {label 'master'}
			
			environment {
				SECRET_ID_01 	= credentials("${SECRET_ID_01}")
			}	
						
            steps {
                echo 'Prepare config file'
				bat 'powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File %WORKSPACE%/.jenkins/replace_web_config_php_script.ps1'

				
				echo 'MSDeploy to server'
				bat '%WORKSPACE%/.jenkins/webdeploy2.bat'
			}
        }
    }
}
